---
title: "MBAM Data CHallenge"
author: "DatArt"
date: "28 janvier 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(MASS)
library(dplyr)
library(ggplot2)
library(readxl)
library(reshape2)
library(grid)
library(gridExtra)
library(data.table)
library(hutilscpp)
library(fastDummies)
library(tidyr)


if (Sys.getenv("USERNAME") =="David"){
  setwd("C:/Users/David/OneDrive/1_Ecole/HEC/Msc/HEC DATA")
}else{
  
  
}

```




```{r import_data, include=FALSE}


complete_df = read.csv("./MBAM_data/MBAM_complet.csv",header = TRUE,encoding = "UTF-8")
complete_df$date = date(complete_df$date)
dict_comlete <- read_excel("./Dictionnaire_MBAM.xlsx",sheet = "Dictionnaire MBAM_complet",col_names = FALSE)


complete_df$campagnes[complete_df$campagnes == "EblastPromoParis-Le Saviez-vous?#1"] <- "EblastPromoParis_LeSaviez-vous?#1"
complete_df$campagnes [complete_df$campagnes == "EblastPromoParis-LeSaviez-vous?#1"]<- "EblastPromoParis_LeSaviez-vous?#1"
complete_df$campagnes[complete_df$campagnes == "EblastPromoParis-LeSaviez-vous?#2"] <- "EblastPromoParis_LeSaviez-vous?#2"
complete_df$campagnes[complete_df$campagnes == "EblastPromoParis-LeSaviez-vous?#3"] <- "EblastPromoParis_LeSaviez-vous?#3"
complete_df$campagnes[complete_df$campagnes == "EblastPromoParis-LeSaviez-vous?#4"] <- "EblastPromoParis_LeSaviez-vous?#4"
complete_df$campagnes[complete_df$campagnes == "EblastPromoParisOK"] <- "EblastPromoParis"

complete_df$campagnes <- gsub("#[0-9]","",complete_df$campagnes)


complete_df_adj <- complete_df %>% filter(!(num_dossier_mbam_coded %in% c("908d1fd10b357ed0ceaaec823abf81bc", "1b94ef47779439aedbf89a519ccb0ac3"))) %>% 
                                  select(-c("campaign_name", "inscription", "lettre","campaign_id","date_envoi","hardbounce","softbounce","complaint")) %>% 
                                  group_by(campagnes, statut,langue) %>%
                                  dummy_cols(select_columns = c("campagnes", "statut","langue" ))

complete_df_adj <- complete_df_adj %>% ungroup() %>% select(-c("campagnes", "statut","langue")) %>% distinct(.keep_all=TRUE) 

all_int_var= names(complete_df_adj)[!names(complete_df_adj) %in% 
                                                     c("num_dossier_mbam_coded", "date","first_transaction")]

testing <- aggregate(.~num_dossier_mbam_coded+date, complete_df_adj %>% select(-first_transaction), any)


write.csv(testing,"Curated_complete.csv")
  

hey <- testing[,grep("campagnes_",names(testing))]
hey$campagned_triggered <- rbinom(p=0.05, n=nrow(hey),size=1)


test2 <- hey %>% pivot_longer(starts_with("campagnes_"),
                              names_to="campagnes",
                              values_to = "triggered",
                              names_prefix = "campagnes_") %>% 
                 group_by(campagnes, triggered) %>% 
                 summarise(Somme= sum(campagned_triggered)) %>% 
                 pivot_wider(names_from=triggered,
                             values_from = Somme,
                             names_prefix= "triggered_") %>% mutate("effective_%" = round(triggered_TRUE/(triggered_TRUE+triggered_FALSE),4)*100 )




```


```{r}
data_date_delivered= complete_df  %>%
        select(c(date,num_dossier_mbam_coded,statut,langue, delivered, open, clicked, not_open,open_but_didnt_click,campagnes)) %>% filter(delivered ==1) %>%
                                            group_by(date) %>% 
                                            summarise(count_date= n(),
                                                      Open= sum(open),
                                                      Clicked= sum(clicked),
                                                      Not_open= sum(not_open),
                                                      Open_not_click= sum(open_but_didnt_click)) %>% mutate(Pct_open = Open/count_date)

data_open_or_not = melt(data_date_delivered %>% select(date, Open, Not_open,Pct_open) ,id.vars = "date")


color_table_1= tibble(open_or_not= c("Open","Not_open"),
                    color=c("green","red"))

g1 <- ggplot(data= data_open_or_not %>% filter(variable!="Pct_open"))+
  geom_col(mapping = aes(x=date,y=value,fill=variable),position="stack") +
  scale_fill_manual(values=color_table_1$color)+
  ggtitle("Les courriels sont-ils ouvert?")+ylab("# courriel envoyés")+ xlab("Date")+
  theme(legend.position = "right",legend.title = element_blank(),
        axis.title.x = element_blank(), axis.text.x = element_blank())

g2 <- ggplot(data= data_open_or_not %>% filter(variable=="Pct_open"))+
  geom_col(mapping = aes(x=date,y=value,fill=variable),position="stack") +
  scale_fill_manual(values=color_table_1$color)+
  ylab(" % courriel ouvert")+ xlab("Date")+
  theme(legend.position = "right",legend.title = element_blank())


g3 <- grid.arrange(g1,g2,ncol=1)




###
data_date_delivered$Open_clicked_pct = data_date_delivered$Clicked / data_date_delivered$Open


ggplot(data= data_date_delivered)+
  geom_col(mapping = aes(x=date,y=Open_clicked_pct),fill="green") +
  ylab("% des courriels ouvert")+ xlab("Date")+ ggtitle("Ça clique ou Ça ne clique pas?")

######

data_date_delivered_campagnes= complete_df %>% 
        select(c(date,num_dossier_mbam_coded,statut,langue, delivered, open, clicked, not_open,open_but_didnt_click,campagnes)) %>% filter(delivered ==1) %>%
                                            group_by(date,campagnes) %>% 
                                            summarise(count_date= n(),
                                                      Open= sum(open),
                                                      Clicked= sum(clicked),
                                                      Not_open= sum(not_open),
                                                      Open_not_click= sum(open_but_didnt_click)) 

data_open_or_not_with_campaign = melt(data_date_delivered_campagnes %>% select(date, Open, Not_open,campagnes) ,id.vars = c("date","campagnes"))


count_campaigne <- data_open_or_not_with_campaign %>% filter(variable=="Open") %>% group_by(campagnes) %>% summarise(count_campagnes= n())
data_open_or_not_with_campaign <- data_open_or_not_with_campaign %>% merge(count_campaigne)

data_open_or_not_with_campaign$campagnes <- gsub("EblastPromoParis_","",data_open_or_not_with_campaign$campagnes)


ggplot(data= data_open_or_not_with_campaign %>% filter(count_campagnes>1))+
  geom_col(mapping = aes(x=date,y=value,fill=variable),position="stack") +
  scale_fill_manual(values=color_table_1$color)+
  ggtitle("Ouvert ou non par campagne")+ylab("Nombre de communication envoyés")+ xlab("Date")+
  theme(legend.position = "None")+facet_wrap(campagnes~.,scales="free",ncol = 4,labeller = label_wrap_gen(width=20))+
  theme(axis.text.x = element_text(angle=45))+
  theme(strip.text.x = element_text(size = 10, colour = "black"))


ggplot(data= data_open_or_not_with_campaign %>% filter(count_campagnes==1),group=color)+
  geom_col(mapping = aes(x=date,y=value,fill=variable,color=campagnes)) +
  scale_fill_manual(values=color_table_1$color)+
  ggtitle("Ouvert ou non par campagne")+ylab("Nombre de communication envoyés")+ xlab("Date")+
  theme(axis.text.x = element_text(angle=45),axis.title.x = element_blank())+
  theme(strip.text.x = element_text(size = 7, colour = "black")) 

```

Analyse des data
Les probleme de courriels
```{r }
#Les hardbounce
ggplot(data=complete_df %>% filter(hardbounce ==1 | softbounce ==1))

complete_df %>% filter(hardbounce ==1 | softbounce ==1) %>% group_by(num_dossier_mbam_coded) %>% summarise()


```

length(unique(complete_df$num_dossier_mbam_coded))




# LES ID pas actifs
```{r }
complete_df_adj <- 

yo <- complete_df %>% 
        select(c(num_dossier_mbam_coded,date,open,statut,converted)) %>% 
        filter(!(num_dossier_mbam_coded %in% c("908d1fd10b357ed0ceaaec823abf81bc",
                                              "1b94ef47779439aedbf89a519ccb0ac3"))) %>%     
        arrange(date)%>% 
        group_by(num_dossier_mbam_coded) %>% 
                mutate(days_since_last_communication= as.numeric(date- lag(date,1)),
                       REGIME_CHANGE ="NEUTRAL") %>% 
                mutate(REGIME_CHANGE= case_when(
                            ((statut=="ACTIFS") & (lag(statut,1)=="INACTIFS"))~"IN",
                            ((statut=="INACTIFS") & (lag(statut,1)=="ACTIFS"))~"OUT",
                              TRUE~REGIME_CHANGE))

yo <-  yo %>% group_by(num_dossier_mbam_coded, date) %>% summarise(statut_adj= case_when("ACTIFS" %in% unique(statut)~"ACTIFS",
                                                                                         "VI"

yo$days_since_last_communication[is.na(yo$days_since_last_communication)] <- 0
yo<-yo %>% 
  group_by(num_dossier_mbam_coded) %>% 
  mutate(Temps_entre_open= cumsum_reset(as.logical(1-open),days_since_last_communication)) %>% 
  mutate(one1=1)%>%
  mutate(nb_courriel_until_converted= cumsum_reset(as.logical(1-converted),one1))


mean_communication_id= yo %>% group_by(num_dossier_mbam_coded) %>% 
                                              summarise(mean_temps=mean(days_since_last_communication),
                                               max_temps= max(days_since_last_communication)
                                               )

melt_mean= melt(mean_communication_id)

ggplot(data= melt_mean) + 
  geom_density(mapping=aes(x=value,fill=variable),alpha=0.5)+ ggtitle("Distribution des temps moyens et maximum\nentre les communication avec les clients")


mean_communication_id_date= yo %>% group_by(num_dossier_mbam_coded,date) %>% summarise(mean_temps=mean(days_since_last_communication),
                                                                             max_temps= max(days_since_last_communication))

ggplot(data=mean_communication_id_date)+
  geom_point(mapping=aes(x=date,y=max_temps),alpha=0.2)

mean_open_id= yo %>% group_by(num_dossier_mbam_coded) %>% mutate(come_back = -Temps_entre_open+ lag(Temps_entre_open,1)) %>% 
                                                          mutate(come_back=case_when(is.na(come_back)~0,
                                                                                     TRUE~come_back)) %>% 
                                                          summarise(mean_open=mean(Temps_entre_open), 
                                                                    max_open=max(Temps_entre_open),
                                                                    max_comeback= max(come_back,na.rm = TRUE))

melt_mean_open= melt(mean_open_id)

ggplot(data= melt_mean_open) + 
  geom_density(mapping=aes(x=value,fill=variable),alpha=0.5)+ ggtitle("Distribution des temps\nentre les ouverture des mail par les clients")+
  facet_grid(variable~.)+ theme(legend.position = "none")


```




```{r }
test <- complete_df %>% 
  group_by(num_dossier_mbam_coded, date) %>% 
  summa,statutrise(statut_day_count=n()) %>% filter(statut_day_count>1) 



```